apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-pythpn-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: yogeshabnave/demo-app:v20251022003323
        ports:
        - containerPort: 5000
