apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudage-app
  namespace: argocd
  labels:
    app: cloudage-education
spec:
  project: default
  source:
    repoURL: https://github.com/YogeshAbnave/eks-pythpn-deployment.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
